### PR TITLE
Fix sidebar mobile

### LINKED ISSUE #998: Реализовать sidebar для мобильной версии
### Цель
Настроить sidebar для мобильной версии

### Функциональные требования
1. sidebar изначально скрыт.
2. открывается на весь экран
3. подменю также открывается на весь экран
4. стили должны соответствовать макету

### Исходный код
**Проект на GitHub:** `https://github.com/Flexberry/ember-flexberry`
**Ветка:** `feature-new-theme`. Создать отдельную ветку на основе, в названии указать номер и краткое наименование задачи.

### Полезные ссылки, скриншоты
Ссылка на макет: https://www.figma.com/file/DJ6lDHNM1BM4mNxJn1jPkC/Flexberry-Guideline?node-id=376%3A155

image
image

### PR DESCRIPTION
**Pull request by pepelyaeva**
#998

### CODE REVIEW

File: addon/components/mobile/flexberry-sitemap-guideline.js [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+    this._super(...arguments);
+    if (this.isDropDown) {
+      this.element.classList.add('item', 'ui', 'dropdown', 'link');
+
+      $(this.element).dropdown({
+        maxSelections: 1,
+        transition: 'slide left',
+        onChange: () => {
+          run.next(() => {
+            let selectedItem = this.targetObject.$('.active.selected');
```
Comment (KollegOFF) [inline addon/components/mobile/flexberry-sitemap-guideline.js]: The `targetObject` property is a private and deprecated API, use jQuery or DOM API to search for elements.

File: addon/components/mobile/flexberry-sitemap-guideline.js [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+    menuToggle() {
+      this.$('.subMenu:first').toggleClass('hidden');
+      this.set('nodeIsOpen', !this.get('nodeIsOpen'));
+    },
+
+    menuBack() {
+      if (this.get('isDropDown')) {
+        $(this.element).dropdown('hide');
+      } else {
+        $('> .menu.visible', this.element).transition('slide left');
```
Comment (KollegOFF) [inline addon/components/mobile/flexberry-sitemap-guideline.js]: Can be replaced by [`this.$`](https://api.emberjs.com/ember/3.1/classes/Component/methods/$?anchor=%24).

File: tests/dummy/app/templates/mobile/application.hbs [hunk 3]
```diff
@@ -27,16 +30,16 @@
           <i class="sidebar icon text-menu-show"></i>
           <i class="sidebar icon hidden text-menu-hide hidden-text"></i>
         </a>
-        <div class="right item">
+        {{!-- <div class="right item">
```
Comment (KollegOFF) [inline tests/dummy/app/templates/mobile/application.hbs]: Why not just delete it?

**Review by KollegOFF — CHANGES_REQUESTED** [review]

**Review by KollegOFF — APPROVED** [review]
